### ISSUE TITLE
No pico is found when example 'blink' is running 

### ISSUE THREAD

**Issue by brtchip-paul-jiao** [MrYsLab/Telemetrix4RpiPico#1]
![image](https://user-images.githubusercontent.com/13127756/125388149-90169080-e3d1-11eb-8b36-10f6a64b66db.png)

`blink-pico.py` is from `https://github.com/MrYsLab/telemetrix-rpi-pico/blob/master/examples/blink.py` without changes but file name. 

My python version is 3.8.2. 
The firmware on the Pico(server) side is from: https://github.com/MrYsLab/Telemetrix4RpiPico/tree/master/cmake-build-release

**Comment by brtchip-paul-jiao** [comment]
Found the root cause. My fault: the PC opened a `tera terminal` and it opened the serial port where Pico is connected with. Therefore,  the Telemetrix is unable to open a valid serial port. Close the `tera terminal` and re-plug the Pico board solves the issue immediately.

**Comment by MrYsLab** [comment]
I am glad you found the problem. Thanks for letting me know.
