### ISSUE TITLE
Is it possible to increase the limit of command length

### ISSUE THREAD

**Issue by brtchip-paul-jiao** [MrYsLab/Telemetrix4RpiPico#11]
currently, MAX_COMMAND_LENGTH is defined as 30 bytes, see below: 

![image](https://user-images.githubusercontent.com/13127756/145147247-2dfa2615-bb2e-42a4-9fb7-417507b5aa39.png)

May I know if it is possible to increase it to 4096 bytes?

**Comment by MrYsLab** [comment]
@ftdi-paul-jiao Thanks for the question. The reason for the limitation is to minimize latency through the system. Having a larger amount of data go across the link may affect the system's responsiveness, so I am not likely to change the imposed limit.
What you may wish to do is fork both the Python and Pico C-SDK repositories and customize things to meet your needs. You can then see if the larger buffer size affects the overall performance of your application.
I am closing this issue, but if you have any questions or comments, please post them here, and I will respond if you have any questions or comments. I will be happy to provide any guidance you might need.
