### ISSUE TITLE
What's wrong with cmake 

### ISSUE THREAD

**Issue by qianshuyuank** [MrYsLab/Telemetrix4RpiPico#13]
[ 95%] Linking CXX executable Telemetrix4RpiPico.elf
[ 95%] Built target Telemetrix4RpiPico
Scanning dependencies of target pio_Telemetrix4RpiPico_Telemetrix4RpiPico_pio_h
[ 96%] Generating ../generated/Telemetrix4RpiPico.pio.h
Can't open output file '/mnt/hgfs/TOC/Telemetrix4RpiPico-2.0/generated/Telemetrix4RpiPico.pio.h'
make[2]: *** [CMakeFiles/pio_Telemetrix4RpiPico_Telemetrix4RpiPico_pio_h.dir/build.make:61：../generated/Telemetrix4RpiPico.pio.h] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1538：CMakeFiles/pio_Telemetrix4RpiPico_Telemetrix4RpiPico_pio_h.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2

![image](https://user-images.githubusercontent.com/10936533/146640391-640bbd80-38a4-4e80-a8e5-3f21aae990cb.png)

**Comment by MrYsLab** [comment]
I use [CLion](https://www.jetbrains.com/clion/) to do my cmake builds. Someone else had an [issue using raw make](https://github.com/MrYsLab/Telemetrix4RpiPico/issues/7), and was able to solve the issue for themselves.

I am not very experienced with cmake, so perhaps the information in issue#7 will help you solve your problem.

**Comment by qianshuyuank** [comment]
> I use [CLion](https://www.jetbrains.com/clion/) to do my cmake builds. Someone else had an [issue using raw make](https://github.com/MrYsLab/Telemetrix4RpiPico/issues/7), and was able to solve the issue for themselves.
> 
> I am not very experienced with cmake, so perhaps the information in issue#7 will help you solve your problem.
Using this step, the compilation passed 
mkdir build
cd build
cmake ..
make Telemetrix4RpiPico
