### ISSUE TITLE
Any plan to add SPI support ? 

### ISSUE THREAD

**Issue by brtchip-paul-jiao** [MrYsLab/Telemetrix4RpiPico#2]

**Comment by MrYsLab** [comment]
It is under consideration, but I haven't decided yet whether to support it or not. What SPI devices do you use?

**Comment by brtchip-paul-jiao** [comment]
I am using embedded GPU : [BT817](https://brtchip.com/bt81x/) which enables MCU to drive LCD through SPI

**Comment by MrYsLab** [comment]
Thanks for the info. Before I commit to doing this, I want to share some information with you to decide if I should proceed with implementing SPI.
1. I can't promise a specific date as to when I would complete this.
2. The main loop of the code works in a round-robin fashion, checking for commands to process and then checking for data changes on input devices.  As a result, the main loop interval is variable because different commands and input devices take different amounts of time to process. If your application requires the BT817 to be serviced within a fixed time period, this may not be an appropriate solution.
3. I will be testing the SPI API using an MPU9250 9-Axis 9 DOF accelerometer. If you have problems programming and controlling the BT817, I can only provide some general guidance since I cannot test the device here.
Please let me know if you are still interested in going ahead with this despite the points above.

**Comment by brtchip-paul-jiao** [comment]
@MrYsLab   Fully understood ! I am still interested in it.

**Comment by MrYsLab** [comment]
@ftdi-paul-jiao I decided to start working on this before I complete my support for the Arduino Nano RP2040 Connect. I can then incorporate SPI there as well.
I created new branches for both the [sketch](https://github.com/MrYsLab/telemetrix-rpi-pico/tree/spi) and the [client](https://github.com/MrYsLab/telemetrix-rpi-pico/tree/spi). 
I will document changes in the README.md files for both if you wish to see how things progress. I will be working on the client first and then the sketch.
Thanks.

**Comment by brtchip-paul-jiao** [comment]
That will be great ! Will follow up on the progress!

**Comment by MrYsLab** [comment]
@ftdi-paul-jiao I am not sure if you have written code to control the BT813 directly either on the Pico or an Arduino, but if you have and can share the code, I would love to see it. I am asking because the SPI support on the Pico is limited when compared to the Arduino SPI library. The clock edge types (rising or falling) cannot be specified on the Pico. Also, bit-order is fixed to MSBFIRST.
I will continue to work on the code, but if any of these limitations impact interfacing to the BT813, please let me know.

**Comment by brtchip-paul-jiao** [comment]
@MrYsLab   Yes. I did write the code for Eve chips .  

Here is some Pico project in C language which works on Eve successfully: 
https://github.com/BRTSG-FOSS/pico-bteve/tree/main/c/basic

In circuitPython,  the application code and library can be found here: 
https://github.com/BRTSG-FOSS/pico-bteve/tree/main/circuitPython

Pico can perfectly work with Eve with its native SPI

**Comment by MrYsLab** [comment]
@ftdi-paul-jiao Thanks. That was very helpful. I added python stubs for all the SPI methods and updated the API. There is a "set_pin_mode_spi" method, and all other spi methods begin with **spi_.** [Here ](https://htmlpreview.github.io/?https://github.com/MrYsLab/telemetrix-rpi-pico/blob/spi/html/telemetrix_rpi_pico/index.html#telemetrix_rpi_pico.telemetrix_rpi_pico.TelemetrixRpiPico.spi_set_format)is a link to the API. The intent is that most folks will use set_pin_mode_spi, spi_read_blocking, and spi_write_blocking, but the other methods are available as well. Please let me know if you have any questions or comments about the methods? I will be coding these in the coming days. When that is complete, I will be implementing the code on the Pico side.

**Comment by MrYsLab** [comment]
@ftdi-paul-jiao I am coding the non-asyncio version of the python code first. Which client do you use, 
telemetrix-rpi-pico or tmx-pico-aio? I will be coding the aio version after I get the non-asyncio version working.

**Comment by brtchip-paul-jiao** [comment]
@MrYsLab  Thanks for your quick update. I am using `telemetrix-rpi-pico` and have not tried `tmx-pico-aio`.

**Comment by MrYsLab** [comment]
@ftdi-paul-jiao I successfully initialized and read data from an MPU9250, so SPI is basically working. I need to do some code cleanup, and provide a fully commented Python example. This should take me about a day or so. I tested with read_blocking and write_blocking. I also want to try using write_read_blocking. I may remove the 16-bit SPI commands since I won't be able to test them adequately. I am not sure how common their use may be.

When things are ready, I will let you know. You may then test things out on your end.

**Comment by brtchip-paul-jiao** [comment]
@MrYsLab   Thank you very mcuh. Looking forward it.

**Comment by MrYsLab** [comment]
@ftdi-paul-jiao 
This branch is ready for you to try out.

**Comment by brtchip-paul-jiao** [comment]
@MrYsLab  Thanks. Will test it and come back to you as soon as possible.

**Comment by brtchip-paul-jiao** [comment]
@MrYsLab  I am testing your code in the latest branch with my SPI (Eve) device. 
```C
addr = [0x30,0x20,0x00]
pico.spi_write_blocking(addr, SPI_PORT) 
```
May I know which byte will be appeared on SPI bus first when the code above runs ? 0x30 or 0x00?

**Comment by MrYsLab** [comment]
@ftdi-paul-jiao 
I can't be positive without connecting a logic analyzer on the output line, but I would think 0x30 would be first. To ensure that the write instruction is being translated correctly from the Python command to the actual Pico command, I ran the following experiment.

I sent a write blocking command using this syntax:
```
pico.spi_write_blocking([0x78, 0x79, 0x63], 0)
```
I added some debug statements on the Pico side to print out how the command is formed before calling the write command. 

```
void write_blocking_spi() {
    spi_inst_t *spi_port;
    uint cs_pin;
    size_t data_length;

    if(command_buffer[SPI_PORT] == 0){
        spi_port = spi0;
    }
    else{
        spi_port = spi1;
    }

    data_length = command_buffer[SPI_WRITE_LEN];
    // write data
    //spi_write_blocking(spi_port, &command_buffer[SPI_WRITE_DATA], data_length);
    for(int i = 0; i < data_length; i++){
        send_debug_info(i, command_buffer[SPI_WRITE_DATA +i]);
    }
}
```
The send_debug_info sends data back to the Python side to be printed on the console.
Here are the results:

```
DEBUG ID: 0 Value: 120
DEBUG ID: 1 Value: 121
DEBUG ID: 2 Value: 99
```
I am not sure if I have answered your question, but I hope this helps.

**Comment by MrYsLab** [comment]
@ftdi-paul-jiao Have you had any time to try this out yet? If you need some help in porting from your original code to this API, please let me know and I will be happy to answer any questions. Thanks.

**Comment by brtchip-paul-jiao** [comment]
@MrYsLab   thanks a lot for your help. 
Here is my code: 
```Python
SPI_PORT = 0
MISO = 4
MOSI = 3
CLK = 2
CS = [5]
CS_PIN = 5

HIGH = 1
LOW  = 0

REG_ID     = [0x30,0x20,0x00]
REG_CHIPID = [0x0C,0x00,0x00]

DUMMY_BYTE_LENGTH = 1  # Eve specific dummy byte for SPI reading transaction

FREQ = 500000

def write_host_cmd(cmd):
    pico.spi_cs_control(CS_PIN,  LOW)
    pico.spi_write_blocking(cmd, SPI_PORT)
    pico.spi_cs_control(CS_PIN,  HIGH)

def the_device_callback(report):
    """
    Verify the device ID
    """
    print("report=",report)

#The addr shall be exact 3 bytes 
def read_eve(addr, number_of_bytes):    
    pico.spi_cs_control(CS_PIN,  LOW)
    pico.spi_write_blocking(addr, SPI_PORT) 
    pico.spi_read_blocking(number_of_bytes + DUMMY_BYTE_LENGTH, SPI_PORT, the_device_callback)  
    pico.spi_cs_control(CS_PIN,  HIGH) 

# initialize the device
pico.set_pin_mode_spi(SPI_PORT, MISO, MOSI, CLK, FREQ, CS, qualify_pins=False)

write_host_cmd([0x44,0,0])
write_host_cmd([0,0,0])
time.sleep(.5)

while True:
    try:
        # Read Chip ID of Eve
        read_eve(REG_ID, 1)
```

The print out from function `the_device_callback`  is as below: 
`report= [13, 0, 2, 66, 124, 1627876338.9497426]`  

Out of them, report[4] `124`(0x7C) is the chip ID Eve shall return.  It is correct. 
Can you please explain what is the meaning of the rest bytes in the `report` ?

**Comment by brtchip-paul-jiao** [comment]
I can boot Eve up and read/write it correctly with Telemetrix SPI APIs.  You did a good job! 


```Python

"""
This example initializes Eve Chip and reads the Chip ID.
"""

import sys
import time

from telemetrix_rpi_pico import telemetrix_rpi_pico

# Instantiate the TelemetrixRpiPico class accepting all default parameters.
pico = telemetrix_rpi_pico.TelemetrixRpiPico()

"""
 CALLBACKS
 
 These functions process the data returned from the Eve
"""


def the_device_callback(report):
    """
    Verify the device ID
    """
    print("report=",report)




# Convenience values for the pins.
# Note that the CS value is within a list
SPI_PORT = 0
MISO = 4
MOSI = 3
CLK = 2
CS = [5]
CS_PIN = 5

HIGH = 1
LOW  = 0

REG_ID     = [0x30,0x20,0x00]
REG_CHIPID = [0x0C,0x00,0x00]

DUMMY_BYTE_LENGTH = 1  #2 for QSPI(Unsupported yet)

FREQ = 500000

def write_host_cmd(cmd):
    pico.spi_cs_control(CS_PIN,  LOW)
    pico.spi_write_blocking(cmd, SPI_PORT)
    pico.spi_cs_control(CS_PIN,  HIGH)


#The addr shall be exact 3 bytes 
def read_eve(addr, number_of_bytes):    
    pico.spi_cs_control(CS_PIN,  LOW)
    pico.spi_write_blocking(addr, SPI_PORT) 
    pico.spi_read_blocking(number_of_bytes + DUMMY_BYTE_LENGTH, SPI_PORT, the_device_callback)  
    pico.spi_cs_control(CS_PIN,  HIGH)    
    
def write_eve(addr, buff):  
    bytes_to_write = addr + buff
    bytes_to_write[0] = addr[0] | 0x80
    pico.spi_cs_control(CS_PIN,  LOW)
    pico.spi_write_blocking(bytes_to_write, SPI_PORT) 
    pico.spi_cs_control(CS_PIN,  HIGH)  

# initialize the device
# These are "non-standard" pin-numbers, and therefore
# the qualify_pins parameter is set to FALSE
pico.set_pin_mode_spi(SPI_PORT, MISO, MOSI, CLK, FREQ, CS, qualify_pins=False)

write_host_cmd([0x44,0,0])
write_host_cmd([0,0,0])
time.sleep(.5)


RAM_G = [0x00,0x00,0x00]  # Has to be 3 bytes address
write_eve(RAM_G, [0xDE,0xAD,0xBE,0xBF])


while True:
    try:
        # Read Chip ID of Eve
        read_eve(REG_ID, 1)
        read_eve(REG_CHIPID, 4)
        read_eve(RAM_G,4)
        time.sleep(.1)
        
    except KeyboardInterrupt:
        pico.shutdown()
        sys.exit(0)
```

**Comment by brtchip-paul-jiao** [comment]
https://github.com/MrYsLab/telemetrix-rpi-pico/blob/18650619d9f0bbd6a9da92400540c599a841ee32/examples/spi_mpu9250.py#L124

I think the `NUM_BYTES_TO_READ` is not required and not aligned with SPI API.

**Comment by MrYsLab** [comment]
@ftdi-paul-jiao That is great! To explain 
```
report= [13, 0, 2, 66, 124, 1627876338.9497426]
```
For every sensor report, the first byte is always the report type. 13 means an SPI report. I added the following to the comment for spi_read_blocking:
```
callback returns a data list:
        [SPI_READ_REPORT, spi_port, count of data bytes, data bytes, time-stamp]

        SPI_READ_REPORT = 13
```
And for every report, the last entry in the list is a timestamp. To use it, you can add code like this:

```
print(time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(1627876338.9497426)))
2021-08-01 23:52:18
```
The second item in the list, 0,  is the SPI port, the third, 2,  is the number of bytes read, and the fourth and fifth is the data returned.

Thanks for pointing out the error in my example. That was a good catch. I fixed it and updated the repository.

I would like to close this issue and publish the repositories. Is that OK with you? 
Also, I will be publishing the asyncio version as well.

**Comment by brtchip-paul-jiao** [comment]
@MrYsLab  Thank you very much for your comments. It is very helpful.  Please close this issue and publish the repo. 
Looking forward to your `asyncio` version too. I have not tried that yet.

**Comment by MrYsLab** [comment]
Thanks go to @ftdi-paul-jiao for the request for SPI support. Version 1.1 contains the SPI support.
