### ISSUE TITLE
Similar project with interesting hardware features

### ISSUE THREAD

**Issue by FilipDominec** [MrYsLab/Telemetrix4RpiPico#6]
*wishlist* PIGPIO [1] is supposed to be ran on Rpi 0, 1, 2, 3, 4 (they are not clear about the new Rpi Pico, though [2]), where it should give convenient access to the I/O pins as well as a range of interesting hardware. Perhaps some of the hardware support could be easily ported, if anybody is interested.

There are some high-level language libraries [3] for PIGPIO access, too. I don't feel they are much relevant to Telemetrix, though.

PS: It would be good to have an overview of similar remote-control-of-microcontroller projects. This can avoid duplication of effort and overall confusion; for instance there is incredible mess in remote-control-of-instrumentation projects [4,5,6]. 

[1] https://github.com/joan2937/pigpio
[2] http://abyz.me.uk/rpi/pigpio/index.html
[3] https://github.com/search?q=PIGPIO
[4] https://github.com/python-data-acquisition/meta/issues/14
[5] https://ethercalc.net/1anmq248ktu6
[6] https://xkcd.com/927/

**Comment by MrYsLab** [comment]
I use pigpio in my Raspberry Pi projects. An example is [a python-banyan gateway for the RPi](https://github.com/MrYsLab/python_banyan/blob/master/projects/OneGPIO/raspberry_pi/rpi_gateway.py).

Could you please explain what you think needs to be done in this project to address the issue?

**Comment by FilipDominec** [comment]
Initially I wanted to keep a link to some potentially useful interfaces to real hardware (like 433MHz key fob, rotary encoder, APA102 LED strip driver, BME280 sensor as listed in http://abyz.me.uk/rpi/pigpio/examples.html#Hardware). Some of them seem already covered (like PCA9685).

Let's mark this as WONTFIX for the moment. Sorry for distraction.

**Comment by MrYsLab** [comment]
No problem. The original intent of Telemetrix was to make it reasonably easy to add support for sensors and actuators of interest. Unfortunately, the Pico C-SDK makes this somewhat difficult. Once I get the Arduino Nano RP2040 Connect code working, which uses the Arduino-Core for the RP2040, I will try porting it for the the serial interface. It is much easier to extend the Telemetrix servers if using an Arduino Core. Many of the existing libraries can work with the RP2040.
