### ISSUE TITLE
Overclocking RP2 to 250+ MHz by default?

### ISSUE THREAD

**Issue by FilipDominec** [MrYsLab/Telemetrix4RpiPico#9]
It seems there is no price to pay for overclocking RP2 twice from default 125 MHz, except for somewhat higher current consumption and few changes in the code. I have no data if ADC's accuracy depends on this. USB throughput seemed not improved nor compromised at 250MHz clock.

The benefits seem important to me; not only will RP2 be capable of handling more tasks/events at once without getting overloaded, its PIO also seems to overclock well so e.g. AD9288 (with pricetag not higher than RP2) could provide  data acquisition at 83.3Msps, or perhaps even at 125Msps. Similarly, RP2 could make a nice logic analyzer and DDS signal generator at similar frequencies. Still there remain many pins left for other uses, which warranties attempts to integrate this functionality into Tmx even though standalone projects exist.

(RP2 was reported to overclock up to 400-420 MHz quite reliably, but above 300MHz USB stopped working in my tests, complying with experience of others. Perhaps this has been resolved meanwhile, but I have no data about this either. We don't have to push it to its extremes anyway.)

Do you think it is a good idea?

**Comment by MrYsLab** [comment]
I stay away from overclocking because it may affect the processor's lifespan. If overclocking enables you to meet the needs of your project and you are willing to take the risk, then it makes sense to do so.

**Comment by FilipDominec** [comment]
OK, let's mark this as WONTFIX for the moment.
